/**************************************************************************
 *
 *  (c) 1992 Joe Jaworski
 *	 18405 Tamarind Street
 *  Fountain Valley, CA 92708
 *	 ALL RIGHTS RESERVED.
 *
 * Created and Written by Joe Jaworski
 * Microsoft C 6.00A, SDK 3.1
 *
 *
 * Revision:	$Revision:   1.4  $
 * Date:			$Date:   20 Feb 1993 09:27:48  $
 * Log File:	$Logfile:   C:/src/st/vcs/resource.h_v  $
 * Log:			$Log:   C:/src/st/vcs/resource.h_v  $
 * 
 *    Rev 1.4   20 Feb 1993 09:27:48   jaworski
 * Initial Revision
 *
 **************************************************************************/

/***********************************/
/*          Star Trek              */
/*     Resource INCLUDE File       */
/*											  */
/* mainly controlled by Workshop	  */	
/***********************************/

#define WAVE 300

#define DLG_SCORE	1

#define BMP_ALERT	1
#define BMP_BTN	2
#define BMP_XBTN	3
#define BMP_DIGITS	4
#define BMP_ABTSHIP	5
#define BMP_PANEL	6
#define BMP_LINEART	7
#define BMP_MEMO 	 8
#define BMP_BTNSRS 10
#define BMP_BTNLRS 11
#define BMP_BTNNAV 12
#define BMP_BTNSHE 13
#define BMP_BTNPHO 14
#define BMP_BTNPHA 15
#define BMP_BTNDAM 16
#define BMP_BTNCOM 17
#define BMP_ENTL 18
#define BMP_ENTR 19
#define BMP_KLINGON 20
#define BMP_ROMULAN 21
#define BMP_BORG 22
#define BMP_FARENG 23
#define BMP_STAR0 24
#define BMP_STAR1 25
#define BMP_STAR2 26
#define BMP_BASE 27
#define BMP_COURSE 28
#define BMP_WARP 29
#define BMP_IMPULSE 30
#define BMP_EXECUTE 31
#define BMP_DIGITSG 32
#define BMP_LRBLOCK 33
#define BMP_SHEDIL  34
#define BMP_SHESHE  35
#define BMP_DAM     36
#define BMP_DIST	  37
#define BMP_PHOTON  38
#define BMP_EXPLKLG  39
#define BMP_EXPLKLGD 40
#define BMP_EXPLROM  41
#define BMP_EXPLROMD 42
#define BMP_EXPLFAR  43
#define BMP_EXPLFARD 44
#define BMP_EXPLBRG  45
#define BMP_EXPLBRGD 46
#define BMP_EXPLBASD 48
#define BMP_SINGWIDE 49
#define BMP_TLOCKBOX 50
#define BMP_TLOCKON  51
#define BMP_PHASBOX  52
#define BMP_CHECKED  53
#define BMP_UNCHKED  54
#define BMP_EXPLENTL 55
#define BMP_EXPLENTR 56
#define BMP_SCORE    57
#define BMP_OPENENT  58


#define IDM_NEW		200
#define IDM_OPEN		201
#define IDM_SAVE		202
#define IDM_SAVEAS	203
#define IDM_ENDGAME	204
#define IDM_EXIT		205

#define IDM_CREWMAN	210
#define IDM_YEOMAN	211
#define IDM_OFFICER	212
#define IDM_1OFFICER	213
#define IDM_CAPTAIN	214
#define IDM_ADMIRAL	215


#define IDM_PAUSE		250
#define IDM_AUTOSRS	251
#define IDM_SINGLE	252
#define IDM_PICONIC	253
#define IDM_SOUNDS	254

#define IDM_CASCADE	260
#define IDM_TILE		261
#define IDM_ARRANGE	262
#define IDM_DEFPOS	263
#define IDM_SAVEDEF	264
#define IDM_RESDEF	265

#define IDM_HELP		280
#define IDM_ABOUT		281


#define IDM_MDI		500
#define IDM_SRS		501
#define IDM_LRS		502
#define IDM_NAV		503
#define IDM_PHO		504
#define IDM_PHA		505
#define IDM_SHE		506
#define IDM_DAM		507
#define IDM_COM		508
#define IDM_PANEL		509
#define IDM_MSG		510
#define IDM_BTN		511


#define	RS_SAVEGAME	   1
#define 	RS_REDALRTSAVE	2
#define 	RS_SAVEQUERY   3
#define 	RS_HSKILL      4
#define 	RS_HPLAY	      5
#define 	RS_BEGIN	 		6
#define 	RS_AUTOSRS 		7
#define 	RS_SINGLE 		8
#define 	RS_PAUSEI 		9
#define 	RS_GEN 			10
#define 	RS_SOUND 		11 
#define 	RS_SRSVAL 		12 
#define 	RS_LRSVAL 		13 
#define 	RS_NAVVAL 		14 
#define 	RS_PHOVAL 		15 
#define 	RS_PHAVAL 		16 
#define 	RS_SHEVAL 		17 
#define 	RS_DAMVAL 		18 
#define 	RS_COMVAL 		19 
#define 	RS_PANVAL 		20 
#define 	RS_BTNVAL 		21 
#define 	RS_MSGVAL 		22 
#define 	RS_POS    		23 
#define 	RS_BTN    		24
#define 	RS_NODAM  		25
#define 	RS_EXTCLASS 	26
#define 	RS_ABOUT 		27
#define	RS_OPENFAIL		28
#define	RS_OPENFAIL2	29
#define	RS_LOADGAME		30
#define	RS_WRITEFAIL	31


#define MG_IENGAGE 100
#define MG_WENGAGE 101
#define MG_STOPPED 102
#define MG_BLOCKST 103
#define MG_BLOCKSB 104
#define MG_BLOCKKL 105
#define MG_BLOCKFA 106
#define MG_BLOCKRO 107
#define MG_BLOCKBO 108
#define MG_DOCKED  109
#define MG_PHOFIRE 110
#define MG_PHOSTAR 111
#define MG_PHOSHIP 112
#define MG_PHOBASE 113
#define MG_PHOLOST 114
#define MG_PHOEMPTY 115
#define MG_PHODEST 116
#define MG_FATAL   117
#define MG_PHAFIRE 118
#define MG_PHAHIT	 119
#define MG_PHANONE 120
#define MG_ENTHIT  121
#define MG_SHEHOLD 122
#define MG_SHEDOWN 123
#define MG_ONSRS 	 124
#define MG_ONLRS   125
#define MG_ONNAV   126
#define MG_ONSHE   127
#define MG_ONPHO   128
#define MG_ONPHA   129
#define MG_ONCOM   130
#define MG_ONDAM   131
#define MG_ONPAN   132
#define MG_ONMSG   133
#define MG_INIMSG1 134
#define MG_INIMSG2 135
#define MG_YELLOW  136
#define MG_GREEN   137
#define MG_RED     138
#define MG_RESUME  139
#define MG_SAVED   140
#define MG_STARHIT 141
#define MG_ALMISS  142
#define MG_SHEHLD2 143

#define DM_MINOR	 500
#define DM_MINORMAX 23

#define DM_MAJNAV  600
#define DM_MAJSRS  601
#define DM_MAJLRS  602
#define DM_MAJSHE  603
#define DM_MAJPHA  604
#define DM_MAJPHO  605
#define DM_MAJCOM  606
#define DM_MAJDAM  607
#define DM_MAJPAN  608
#define DM_MAJMSG  609
#define DM_ADDNAV  610
#define DM_ADDSRS  611
#define DM_ADDLRS  612
#define DM_ADDSHE  613
#define DM_ADDPHA  614
#define DM_ADDPHO  615
#define DM_ADDCOM  616
#define DM_ADDDAM  617
#define DM_ADDPAN  618
#define DM_ADDMSG  619
#define DM_KILNAV  620
#define DM_KILSRS  621
#define DM_KILLRS  622
#define DM_KILSHE  623
#define DM_KILPHA  624
#define DM_KILPHO  625
#define DM_KILCOM  626
#define DM_KILDAM  627
#define DM_KILPAN  628
#define DM_KILMSG  629


#define COM_INIT    200
#define COM_CURRLOC 201
#define COM_INVALID 202
#define COM_MANUAL  203
#define COM_STARDATE 204
#define COM_POWER   205
#define COM_ALIEN   206
#define COM_NORIC	  207
#define COM_NORIC2  208
#define COM_COMRIC  209
#define COM_BASELOC 210
#define COM_BASEERR 211
#define COM_BASEDIR 212
#define COM_SCAN1	  213
#define COM_SCANBAS 214
#define COM_SCANSTR 215
#define COM_SCANKLI 216
#define COM_SCANROM 217
#define COM_SCANBRG 218
#define COM_SCANFRG 219
#define COM_PHODATA 220
#define COM_RICCOUNT	221
#define COM_SCANSTR2 222
#define COM_XYERR		224
#define COM_SECTDIR	225
#define COM_REROUTE	226
#define COM_UNROUTE	227
#define COM_MSGRER	228
#define COM_MSGUNR	229
#define COM_SRSBUSY	231
#define COM_DAMMSG	232
#define COM_DAMPAN	233
#define COM_DAMSRS	234
#define COM_DAMLRS	235
#define COM_DAMNAV	236
#define COM_DAMSHE	237
#define COM_DAMPHA	238
#define COM_DAMPHO	239
#define COM_DAMDAM	240
#define COM_BADADV	241
#define COM_DOSCMD	242 
#define	COM_ANAHEAD	243
#define	COM_ANAGAM	244
#define	COM_ANANOW1	245
#define	COM_ANANOW2	246
#define	COM_ANAREQ	247
#define	COM_ANAANA1	248
#define	COM_ANAANA2	249

#define RD_OPEN	1
#define RD_ENERGY 2
#define RD_TIME	3
#define RD_SYS		4
#define RD_WIN		5


#define ICN_MAIN	1
#define ICN_PANEL	2
#define ICN_MSG	3
#define ICN_BTN	4
#define ICN_SRS	5
#define ICN_LRS	6
#define ICN_NAV	7
#define ICN_PHO	8
#define ICN_PHA	9
#define ICN_SHE	10
#define ICN_DAM	11
#define ICN_COM	12

#define MNU_EMPTY	1
#define MNU_FULL	2


#define SND_BACK  1
#define SND_CODE1 2
#define SND_EXEC  3
#define SND_EXPLO 4
#define SND_IMP	5
#define SND_OPEN  7
#define SND_PHAS  8
#define SND_PHOT  9
#define SND_PHX	10
#define SND_PHX2  11
#define SND_REDA  12
#define SND_SONG  13
